[package]
name = "dataverse-fake-webapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5"
regex = {version = "1.10", default-features = false, features = ["std"]}
once_cell = "1.18"
